version: '3'
services:
  web:
    image: market-backstage:0.1.0
    volumes:
      - /usr/share/zoneinfo/Asia/Shanghai:/etc/localtime
      - .:/app
    env_file:
      - .env
    environment:
      - TZ=Asia/Shanghai
      - FLASK_ENV=${FLASK_ENV:-development}
    ports:
      - "5000:5000"
    restart: always
    command: flask run -h 0.0.0.0
    depends_on:
      - redis
  redis:
    image: redis:alpine
networks:
  default:
    external:
      name: market-backstage
