version: '3'
services:
  web:
    image: market-backstage:${VERSION}
    volumes:
      - web-logs:/app/${LOG_PATH}
    env_file:
      - .env
    environment:
      - TZ=Asia/Shanghai
      - FLASK_ENV=${FLASK_ENV:-development}
    ports:
      - "5000:5000"
    restart: always
    command: gunicorn
        autoapp:app
        --bind 127.0.0.1:5000
        -w 8
        -k eventlet
        --access-logfile -
        --error-logfile -
    depends_on:
      - redis
    healthcheck:
      test: ["CMD", "curl", "-f", "localhost:5000/api/v1/configs/ping" ]
      interval: 5s
      timeout: 5s
      retries: 3
  redis:
    image: redis:alpine
networks:
  market-backstage:
    external: true
volumes:
  web-logs:

