"""交互信息相关的常量"""

# Global Exceptions Message
SERVER_LOG_ERROR = 'SERVER ERROR'
SERVER_UI_ERROR = 'SERVER ERROR, PLEASE CONTACT THE MANAGER'
NOT_FOUND_ERROR = '404 NOT FOUND'
RECORD_NOT_FOUND_ERROR = 'RECORD NOT FOUND'
